export const Products = [
    {
        id: "1",
        title: "Guantes Everlast",
        price: 2500,
        stock: 15,
        imageUrl: "a",
        description: "La mejor calidad en guantes",
        brand: "Everlast",
        category: "Guantes",
    },

    {
        id: "2",
        title: "Guantes Winning",
        price: 5500,
        stock: 9,
        imageUrl: "a",
        description: "Guantes echos especialmente a mano ",
        brand: "Winning",
        category: "Guantes",
    },
    {
        id: "3",
        title: "Guantes Corti",
        price: 3000,
        stock: 25,
        imageUrl: "a",
        description: "La mejor calidad nacional",
        brand: "Corti",
        category: "Guantes",
    },
    {
        id: "4",
        title: "Vendas Boxeo Everlast",
        price: 500,
        stock: 35,
        imageUrl: "a",
        description: "Vendas de 4mts",
        brand: "Everlast",
        category: "Vendas",
    },
    {
        id: "5",
        title: "Vendas Boxeo Adidas",
        price: 1000,
        stock: 17,
        imageUrl: "a",
        description: "Vendas Adidas 5mts",
        brand: "Adidas",
        category: "Vendas",
    },
    {
        id: "6",
        title: "Vendas Proyec",
        price: 950,
        stock: 23,
        imageUrl: "a",
        description: "Vendas Proyect 5mts",
        brand: "Proyec",
        category: "Vendas",
    },
    {
        id: "7",
        title: "Cabezal Amateur",
        price: 6000,
        stock: 5,
        imageUrl: "a",
        description: "Cabezal para Sparrings",
        brand: "Corti",
        category: "Equipamiento",
    },
    {
        id: "8",
        title: "Protector bucal",
        price: 300,
        stock: 40,
        imageUrl: "a",
        description: "Protector Efectivo para el cuidado de los dientes",
        brand: "Everlast",
        category: "Equipamiento",
    },
    {
        id: "9",
        title: "Protector Inguinal",
        price: 1300,
        stock: 10,
        imageUrl: "a",
        description: "Protector Efectivo para el cuidado de las zonas bajas",
        brand: "Adidas",
        category: "Equipamiento",
    }

]